# syntax=docker/dockerfile:1

FROM node:20.19-alpine3.21
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./
RUN npm ci

COPY src/ ./src/

CMD ["npx", "tsx", "src/worker.ts"]
