services:
  web:
    build: .
    container_name: pyramid-portfolio
    ports:
      - '3400:3400'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: pyramid-worker
    env_file:
      - .env
    restart: unless-stopped
